version: '3.8'

services:
  php:
    build: .
    ports:
      - "8080:80"    # Maps host port 8080 to container port 80
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: clinic_db
      MYSQL_USER: clinic_user
      MYSQL_PASSWORD: clinic_password
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"         # phpMyAdmin will be accessible on http://localhost:8081
    environment:
      PMA_HOST: db        # Connects phpMyAdmin to your MySQL container
      PMA_PORT: 3306

volumes:
  db_data:
